### PR TITLE
remove `bg_buf` and `bg_win` from floating window

### PR DESCRIPTION
**Pull request by numToStr**
As you can see in the screenshot, the current floating window looks broken. So, I changed the highlights, dimensions, and added borders to make it look nice. Need feedback on how it looks on different themes.

Before:
image

After:
image

Thoughts? @wbthomason

### CODE REVIEW

**Comment by katsika** [comment]
It's not broken on my colorscheme. And not everyone likes borders. 

Would be nice if for example plenary provided configurable floating windows and Packer reused that code rather than adding window management to the plug-in which should have nothing to do with it.

**Comment by wbthomason** [comment]
@numToStr Thanks for the PR! This is good work.

I'd be happy to merge the bounds fixes, but I would like to keep the `open_fn` as minimal as possible - per the original request that led to it being added (#75), this is meant to be a minimal "it just works" floating display. I think I would actually prefer to remove the `bg_buf` entirely, rather than adding a border. What do you think?

@katsika: It would indeed be nice if somewhere provided configurable floating windows; unfortunately, unless we want to depend on every `packer` user having `plenary` (which I do not want to depend on), this would need to come from Neovim core. For the time being, I'm just trying to keep the floating window code simple and minimal.

**Comment by numToStr** [comment]
> I think I would actually prefer to remove the `bg_buf` entirely, rather than adding a border. What do you think?

Yeah, this makes perfect sense to me. Would you mind if I the remove the `bg_buf` and update this PR?

**Comment by wbthomason** [comment]
Sounds great, thank you!

**Comment by numToStr** [comment]
@wbthomason I removed the `bg_win` and `bg_bug`. Now its ready to review.

**Review by wbthomason — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
