### PR TITLE
feat: keep compiled script same order with declaration

### PR DESCRIPTION
**Pull request by alannotnerd**
I found it will be confused if the script keeps changing after compiling, even if the plugin specifications are not changed. So I made a minor change to improve.

### CODE REVIEW

**Comment by alannotnerd** [comment]
It's mainly caused by the order of `pairs` is unspecified in Lua.

**Comment by lewis6991** [comment]
This isn't documented at all and makes the code much harder to understand.

**Comment by alannotnerd** [comment]
It's a minimal change for myself to use. We should use an array-like table for plugins, just like plugin-descriptions did.  If that is acceptable, I will put more commits to make it understandable. :P

**Comment by alannotnerd** [comment]
@lewis6991 I have a simple look for your PR. It's really a great job. I guess I should close this PR till yours merged.

**Comment by yyy33** [comment]
I have installed the vim-notify plugin and I want it to be loaded before all plugins, so I have to add the after field to the configuration of all other plugins, it's too much trouble. How can I specify the order in which plugins are loaded by declaring them, please @alannotnerd

**Pull request closed without merging**
