### PR TITLE
auto add * in event

### PR DESCRIPTION
**Pull request by glepnir**
no need to write '*' in event keyword.

### CODE REVIEW

**Comment by akinsho** [comment]
I wonder if this change doesn't make things much less versatile? I mean I always just use `Event *` but I guess people could otherwise do really custom things like `BufRead .bashrc` or `SessionLoadPost custom_thing` etc. and this would take that ability away entirely 🤷🏿

**Comment by glepnir** [comment]
this behavior like dein `on_event` .

**Comment by akinsho** [comment]
@glepnir its similar but I'm just pointing out that this change trades off customisability, which I guess in some cases might be a lot to lose to avoid having to type in ` *`.

Imagine I had some `zsh` plugin that I only used for editing my `.zshrc` which might be something I do a lot and I wanted to only load that plugin just for `.zshrc` currently I can do `BufRead .zshrc` and this would only load that plugin if I was ever to enter my zshrc. But with this change I would have to always load it on `BufRead`. I could also try `ft = {'zsh'}, event = {'BufRead'}` but that still wouldn't be exactly equivalent.

Anyway it's ultimately up to @wbthomason when he's free, think he's quite busy atm.

**Comment by glepnir** [comment]
I don't think it makes sense. ft is more useful in this situation. dein has been around for a long time. The `on_event` keyword has not been changed to prove that this requirement is not practical

**Comment by akinsho** [comment]
This is just my 2 cents  as I noted this is one for wbthomason ultimately (butting out now) but I don't think it working just like `dein` should be the objective 🤷🏿‍♂️ especially if there's an opportunity to provide some extra value. To be clear it's not just about `filetype` you can do quite a lot of stuff
```lua
use {"someone/plugin", event = {"BufRead *$ENVIRONMENT_VAR/*subdir*/*.txt*"}}
```
To say only load a particular plugin when you are in a specific directory, there are a lot of possibilities.

**Comment by glepnir** [comment]
you can use `cond` ? I think this also can do it.

**Comment by akinsho** [comment]
I think `cond` is only run once when you enter neovim, whereas an autocommand can get triggered at any point during the running vim session, so it wouldn't do the same thing

**Comment by glepnir** [comment]
It should not be just hypothesis. Specific examples can illustrate the problem. Instead of some/plugin. I don't know what plugin only works for txt?

**Comment by nanotee** [comment]
Just as a heads up, I have the exact use case that @akinsho described:

```lua
use {
    'lervag/wiki.vim',
    event = 'BufReadPre ~/Documents/wiki/*.md'
}
```

I'm happy to find another solution if this PR makes `packer` easier to use, but I do like the flexibility of the current API :)

**Comment by glepnir** [comment]
Now both work.

```lua
'BufReadPre','BufReadPre *','BufReadPre ~/Documents/wiki/*.md'
```

**Review by wbthomason — APPROVED** [review]
Thanks all for the contribution and conversation! While I agree with @akinsho and @nanotee that removing the ability to specify an autocommand pattern would be bad, I'm happy with this change to allow both patterns and elided *. Thanks again!

**Pull request merged**
