### PR TITLE
Check that a lazy-load command does not already exist before creating it

### PR DESCRIPTION
**Pull request by wbthomason**
This PR adds a check around each lazy-load command creation to only create the lazy-load command if a command with the same name does not already exist.

This should fix issues like https://github.com/kyazdani42/nvim-tree.lua/issues/471 and #442.

@gegoune: If you have a chance, could you please try this with the `nvim-tree` use case you described on Gitter?

### CODE REVIEW

**Comment by wbthomason** [comment]
Also note that this feature will not work with #408 as planned.

**Comment by wbthomason** [comment]
Also @rafamadriz, if you have a chance to see if this fixes #442, that would be helpful too!

**Comment by TheBlob42** [comment]
I tested this branch in regards to #442 as I just experienced the same error as @rafamadriz and for me it fixes the issue :slightly_smiling_face:

**Comment by wbthomason** [comment]
> Also note that this feature will not work with #408 as planned (as far as I know, there's no way to use `exists` with a pattern?).

I'm dumb - this is fine with #408, just redundant. If the command already exists, then `CmdUndefined` wouldn't fire, so we'd be fine.

**Comment by gegoune** [comment]
@wbthomason It does seem to work now, nicely done! Have tested with Neogit rather than nvim-tree.

I am not sure if that is the result of this PR but after moving configuration fo neogit from `after/plugin` to `config` function in packer nvim has to be restarted for neogit's configuration changed to take effect.

Also, on unrelated note, I was thinking if it is possible to guard configurations in `after/plugin/*` in case given package was not loaded. Do you know of a way?

**Comment by wbthomason** [comment]
Good point. This will prevent `load` from running the new config after an update...

We could hack around that by, in the reload logic in `packer.lua`, checking if a plugin is currently loaded and running its `setup` and `config` fields if it is.

re: `after/...`: I'm not 100% sure I know what you mean by guarding the configurations in case a given package was not loaded. You can use the `_G.packer_plugins` table to check if a given plugin is currently loaded (there's a boolean field `loaded`); this is how `packer.status` checks plugin load state.

**Comment by rafamadriz** [comment]
> Also @rafamadriz, if you have a chance to see if this fixes #442, that would be helpful too!

@wbthomason Awesome, that is working for me!!! May I ask when you think this will get merged ?

**Comment by wbthomason** [comment]
@rafamadriz I've just now pushed a tentative fix to the issue @gegoune noticed. If that works (I've tested it, but not thoroughly yet), then I think this is good to merge.

**Comment by wbthomason** [comment]
@rafamadriz @gegoune Any chance you've been able to test this branch since the latest commit?

**Comment by gegoune** [comment]
I have since removed any lazy loading. Could test it later today though.

**Comment by rafamadriz** [comment]
@wbthomason Yes I was running this branch for a couple of days, didn't have any problem.

**Comment by wbthomason** [comment]
@gegoune It should be ok, but thanks for the offer!
@rafamadriz Great, thanks! I think, from some additional testing of my own, that this branch is still not running the changed configs correctly, but at least it isn't breaking things further and does fix the problem of commands being deleted. Probably good to merge today.

**Comment by ram02z** [comment]
Would like to also add that I have been running this branch for a week and I have no issues either.

**Comment by wbthomason** [comment]
I'm going to merge this for now - while it doesn't 100% solve the problem (updated configs are still not being sourced correctly), it does fix the main breakage of this issue. I'll try to get to the remaining work in another PR soon, unless someone beats me to it.

**Pull request merged**
