### PR TITLE
Fix: Add `--depth 1` flag to clone faster

### PR DESCRIPTION
**Pull request by NarutoXY**
This will result in a blazing fast clone speed even on slow 3g networks.

### CODE REVIEW

**Comment by akinsho** [comment]
@wbthomason this is a small README change WDYT? I think the speed improvement would be good but I was wondering how it would behave if a user tried to change their packer commit or change branches etc. will this end up meaning people who use the docs like this will have to deepen things first so might introduce a new class of issues?

**Comment by akinsho** [comment]
Fair point 👍🏿

**Comment by bnjmnt4n** [comment]
What about adding `--depth 1` to https://github.com/wbthomason/packer.nvim#bootstrapping as well?

**Comment by wbthomason** [comment]
Sorry for the lag; still catching up on issues etc. after my absence. Thanks for handling this @akinsho. I'll add a commit now to resolve @bnjmnt4n's point.

**Pull request merged**
