### PR TITLE
Return value in try_loadstring

### PR DESCRIPTION
**Pull request by gbrlsnchs**

### CODE REVIEW

**Review by wbthomason — APPROVED** [review]
Thanks!

**Comment by gbrlsnchs** [comment]
@wbthomason Just a heads-up, I quickly fixed and rebased this PR because the value I should return was the second one returned by `pcall` and not the first. You merged it correctly but you probably only saw the first version, so I just wanted to let you know.

**Comment by wbthomason** [comment]
Thanks! I actually did see the second version before merging; I was going to patch that issue myself after seeing just the first version, but you beat me to it.

**Comment by gbrlsnchs** [comment]
Haha all good then! :smile_cat:

**Pull request merged**
