### PR TITLE
fix: windows related bugs

### PR DESCRIPTION
**Pull request by TimUntersberger**
Fixed the problems mentioned in #43 .

# Fixes

### in lua numbers are always true

> When used as control expression, the only false values in Lua are false and nil , everything else is evaluated as true value

This means that the following if statement is always true, because `vim.fn.executable` returns a number

```lua
vim.fn.executable('ln')
```

### `mklink` requires admin privileges

In Windows 10 you need to have developer mode enabled to use local plugins. This should probably be mentioned in the README.

I don't know where to put this, so could you please do this?

### `mklink` signature

`mklink` has the `from` and `to` swapped.

### powershell instead of cmd

It looks like your job lib is using powershell and not cmd. This means that you have to use `cmd /C mklink ...` instead of `mklink ...`

### mklink doesn't automatically create directory symlinks

Don't think I need to explain this. You just forgot the `/d` flag of `mklink`.

### CODE REVIEW

**Review by wbthomason — APPROVED** [review]
These are very helpful, thank you!

**Comment by wbthomason** [comment]
I think the correct addressing to your remaining comment about changing the separator in `get_plugin_full_name` may be valid but is better addressed by a refactoring of the (currently messy and overloaded) way I use plugin full vs short names. I've made #47 to track that.

If the current version of this PR isn't any more broken for you, and actually fixes #43 on Windows, I'll go ahead and merge it.

Thank you again for the help!

**Comment by TimUntersberger** [comment]
I am now using this PR and I haven't noticed any problems yet.

lgtm

**Comment by wbthomason** [comment]
Great, thank you again!

**Pull request merged**
