### PR TITLE
fix(git): remove `.git` from end url only

### PR DESCRIPTION
**Pull request by EdenEast**
Removes `.git` from url only if it ends with `.git`.

Resolves: #1022

### CODE REVIEW

**Review by akinsho — APPROVED** [review]
LGTM thanks for the fix

**Comment by axieax** [comment]
@akinsho @EdenEast don't think the Lua pattern is entirely correct. `%s.git` matches a space character, then any character, then "git". The expected pattern should be `%.git`. I have corrected this in #1027.

This breaks the urls detected by my plugin [urlview.nvim](https://github.com/axieax/urlview.nvim).

**Comment by akinsho** [comment]
@axieax thanks for raising this and the PR, didn't notice the issue 🤦🏿‍♂️

**Comment by EdenEast** [comment]
Ah thanks @axieax for the catch sorry about that, my mistake 🤦 .

**Comment by axieax** [comment]
No worries :))

**Pull request merged**
