### PR TITLE
Add plugin alias feature to close #28

### LINKED ISSUE #28: Custom name
How do I do the vim-plug equivalent of `Plug 'dracula/vim', { 'as': 'dracula' }` (ie install it in a folder named `dracula` or else it would be installed in a folder named `vim` because the repository is [https://github.com/dracula/***vim***](https://github.com/dracula/vim))

### PR DESCRIPTION
**Pull request by wbthomason**
Adds the `as` keyword to allow plugins to be installed under aliases. Closes #28

### CODE REVIEW

**Comment by p00f** [comment]
Like this `{'dracula/vim', as = 'dracula'},`?

**Comment by wbthomason** [comment]
Yep! That's a good point; I need to update the docs too.

**Comment by p00f** [comment]
Ik i'm being lazy, but waht if i simply add `branch = feat-add-plugin-aliases` ?

**Comment by wbthomason** [comment]
That should work; if it doesn't, the code for handling branch checkouts has bugs (which is possible; to my knowledge that code hasn't been used/tested much yet).

**Comment by p00f** [comment]
Branch checkout code works, it uses the correct branch. Changed branch, updated packer, packercompile, deleted old `vim` folder, packerinstall. It cloned into `vim` again

**Comment by p00f** [comment]
Can you try it?

**Comment by wbthomason** [comment]
Yes, I've tried that exact sequence, and it installs to `dracula` for me. You shouldn't need the `PackerCompile` invocation in the middle, but that also shouldn't matter.

Sorry for all the hassle, but could you manually confirm that `packer` is on the right branch?

I may also just go ahead and merge this; I'm fairly confident from my own testing that it at least doesn't break things.

**Comment by p00f** [comment]
Sure!

**Comment by p00f** [comment]
Can you check if it appears in `PackerClean` though? After [this](https://github.com/wbthomason/packer.nvim/issues/29#issuecomment-671675946), `as` works but `dracula` appears in PlugClean

**Comment by wbthomason** [comment]
Good catch, thank you! I've pushed bd1ccec which should fix this.

**Comment by wbthomason** [comment]
I'll also note that if you ever *change* an alias, right now we don't have a good way to detect the change, so what happens is the plugin gets reinstalled under the new alias and the next `clean` operation you run will delete the copy under the old alias. This isn't ideal, so I'll try to figure out a better solution in the future.

**Pull request merged**
