### PR TITLE
Fix #100: copy existing environment variable values

### LINKED ISSUE #100: PackerInstall fails
After 06caefb116998aa60fab37e54137942da4de4755 / #91 `:PackerInstall` fails. This is on a network that requires a proxy and it looks like the existing environment variable `https_proxy` is no longer used. Adding that variable to the env config in `lua/packer/plugin_types/git.lua` fixes the issue. It seems like it would make sense to keep the old behavior of using variables that are already set rather than needing to add this additional configuration.

### PR DESCRIPTION
**Pull request by wbthomason**
Copy the entire environment before assigning `GIT_TERMINAL_PROMPT`

### CODE REVIEW

**Comment by ranebrown** [comment]
I'm getting this error `[packer] Error in coroutine: ...k/packer/opt/packer.nvim/lua/packer/plugin_types/git.lua:126: attempt to call field 'os_environ' (a nil value)`

**Comment by wbthomason** [comment]
Hmm, ok. Could you please post your Neovim version? I cannot reproduce that failure on my end right now.

**Comment by ranebrown** [comment]
NVIM v0.5.0-7c4f34966
Build type: Release
LuaJIT 2.0.5

**Comment by wbthomason** [comment]
Thanks @nanotee and @ranebrown for help testing! Please let me know if this does not fix the issue (as I've still been unable to reproduce #26, etc.)!

**Comment by ranebrown** [comment]
Seems to be working. Thanks!

**Pull request merged**
