### PR TITLE
Fix #312: Correctly generate profiling code for conditionals

### LINKED ISSUE #312: optional plugins loads even if cond is false
For a while now I have used the cond-option for a plugin, to temporarily disable plugins with `function() return true end` and `function() return false end` to enable and disable plugins. Today I found all my plugins loaded even if I had it turned off with the function returning false. Example:

This worked previously, but does not work now:

```Lua
use {'seblj/nvim-tabline',
    cond = function() return false end
}
```

### PR DESCRIPTION
**Pull request by wbthomason**
Fixes #312 by special-casing the profiling code generation for conditionals. This is necessary because - unlike for other kinds of timed chunk - we cannot easily put `time` calls around the chunk in the conditional syntax.

@seblj, @yutkat, @yujinyuz: can you confirm that this fixes #312 for you without causing new issues? It works for me on the minimal reproducer. Thanks!

### CODE REVIEW

**Comment by seblj** [comment]
It works for me!

**Comment by yujinyuz** [comment]
works for me too! had to delete the previous `packer_compiled.vim` before it worked

**Comment by yutkat** [comment]
It works! Thank you for your quick fix.

**Comment by wbthomason** [comment]
Sorry for the quick fix but slow merge! :sweat_smile: I got caught up with other work and forgot to merge this. Doing so now - thanks for the help testing the patch!

**Pull request merged**
