### PR TITLE
feat: enable :PackerUpdate/Install/Sync to operate on specific plugins

### PR DESCRIPTION
**Pull request by shadmansaleh**
- Now :PackerUpdate/Install/Sync can be used to operate on specific plugins
- PackerLoad now uses <f-args>

### CODE REVIEW

**Comment by wbthomason** [comment]
Thanks, this looks good - I particularly like the `plugin_complete` inclusion.

While we're extending the update command, it might make sense to apply the same changes to the install and sync commands, the functions for which also optionally take a plugin argument.

**Comment by shadmansaleh** [comment]
> it might make sense to apply the same changes to the install and sync commands

Indeed . Is there a marker for which plugins are installed or not installed ?

**Comment by wbthomason** [comment]
I'm not sure I understand - what do you mean by "a marker"?

**Comment by shadmansaleh** [comment]
> Not currently, but I think the plugin_complete function as it is will be fine to start. Installing an already-installed plugin is a nullop.

Right plugin_complete will be enough . Checking which plugins aren't installed will require lots of fs operations.

**Comment by shadmansaleh** [comment]
Huh didn't think there were tests to fail :P . The runner had a stroke while grabing neovim archive .

Why are you guys still running tests against nightly instead of v0.5 ?

**Comment by wbthomason** [comment]
Honestly, because the test infrastructure for `packer` doesn't get the attention it needs. I'll see about updating the tests to use both 0.5 and nightly in a separate PR; we can ignore the failing tests for now, as we don't test anything that this PR should affect anyway.

**Review by wbthomason — APPROVED** [review]
LGTM, thanks!

**Comment by shadmansaleh** [comment]
> I'll see about updating the tests to use both 0.5 and nightly in a separate PR

You can checkout [shadmansaleh/lualine.nvim](https://github.com/shadmansaleh/lualine.nvim/blob/master/.github/workflows/ci.yml) I had recently updated it to use both nightly and 0.5 . But later disabled nightly as nightly had disappeared :P

**Pull request merged**
