### PR TITLE
Feature: detect repo changes

### PR DESCRIPTION
**Pull request by wbthomason**
This is #340, plus my commits to fix up normalizing plugin URLs and tweak the awaiting of the main thread (it should happen as close as possible to the slow Vim function calls that require it).

### CODE REVIEW

**Comment by wbthomason** [comment]
@nanotee and @akinsho (and anyone else), if you're able to verify that this still works for you, that would be great!

**Comment by akinsho** [comment]
@wbthomason yep still works 👍🏾

**Review by akinsho — APPROVED** [review]
@wbthomason LGTM tested with a non ssh url though but I'm assuming that works for you

**Comment by nanotee** [comment]
@wbthomason I'm not sure what's causing this but I'm getting an error when I run `:PackerSync`:

```
async.lua:20: Error in coroutine: ...site/pack/packer/sta.../lua/packer/update.lua:58: E5560: vimL function must not be called in a lua loop callback
```

What's weird is that this only happens some of the time. Restarting nvim is usually enough to get rid of the error

Changing a plugin's repository still works as expected

**Comment by akinsho** [comment]
It might relate to having moved the `a.wait(main)`, I was getting that during the initial development till I moved it to the line it was previously at.

**Comment by wbthomason** [comment]
Yes, I missed a case to cover with a main thread schedule. I'll fix it when I'm back at my laptop.

**Comment by wbthomason** [comment]
> @wbthomason LGTM tested with a non ssh url though but I'm assuming that works for you

Yup, I tested both cases of my git config.

**Comment by wbthomason** [comment]
@nanotee I believe I've fixed the error you noted, though it required adding more main thread schedules than I expected. It doesn't belong in this PR, but I should see if I can move away from using functions which must be run on the main thread to alleviate this burden.

**Comment by nanotee** [comment]
@wbthomason Seems to have fixed it! I can't reproduce the error anymore

**Comment by wbthomason** [comment]
Ok, I think we're good to merge this (again). Sorry for the churn; hopefully I haven't missed any edge cases this time.

**Comment by oblitum** [comment]
After this commit `:PackerSync` will remove and reinstall any repo I use outside github (e.g. repos from gitlab which use whole https urls).

**Pull request merged**
