### PR TITLE
Show full URLs for PackerSync and PackerStatus. Fixes #542

### LINKED ISSUE #542: Full names (or urls?) in PackerStatus
It would be nice if PackerStatus showed either the full name (eg `wbthomason/packer.nvim` instead of just `packer.nvim`) in PackerStatus, or maybe even the full github url when you hit enter to get more information. PackerSync shows the full names but just for a moment then they're gone unless there were updates.

Sometimes I forget that I'm on a fork of a plugin if I was trying something out.

### PR DESCRIPTION
**Pull request by dsully**

### CODE REVIEW

**Comment by wbthomason** [comment]
Sorry, I've been busy and away from `packer` lately. Taking a look now.

**Review by wbthomason — APPROVED** [review]
Looks good to me, thank you!

**Comment by dsully** [comment]
No problem! Thanks for merging!

**Comment by will** [comment]
Thanks!

**Pull request merged**
