### PR TITLE
chore: move default compile_path under $XDG_DATA_HOME

### PR DESCRIPTION
**Pull request by TheLudd**
The old location is usually under source control, which was not optimal
for generated files. The new location is more suitable for automated
output and is still in the runtimepath.

### CODE REVIEW

**Comment by mcepl** [comment]
I don’t think this is a good idea without the automagic migration from the old place to the new one.

**Comment by TheLudd** [comment]
But this is a generated file for performance purposes? If it does not exist, it will just be re-generated. Will users even notice?

**Comment by mcepl** [comment]
Ah, I see. You are talking about just about `packer_compiled.lua`? Yes, that should really not be in `~/.config/nvim` tree.

**Review by mcepl — APPROVED** [review]
LGTM

**Comment by TheLudd** [comment]
Any thoughts on this? If it looks good, can there be a merge?

**Review by mcepl — APPROVED** [review]

**Comment by TheLudd** [comment]
Once again, this thumbed up, approved, LGTM PR is rebased and ready for merge :smile:

**Comment by thetic** [comment]
https://github.com/wbthomason/packer.nvim/blob/master/README.md?plain=1#L3

**Pull request closed without merging**
